apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-rootusername: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-express-web-username: cm9vdA==
  mongo-express-web-password: cm9vdA==
