apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      imagePullSecrets:
        - name: docker-hub-private
      containers:
      - name: secret
        image: amigoscode/private
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
