apiVersion: v1
kind: Pod
metadata:
  name: sampleapp
  labels:
    name: sampleapp
spec:
  containers:
  - name: sampleapp
    image: jassyboy/sampleapp:V23
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
