apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000


---
apiVersion: v1
kind: Service
metadata:
  name: sonarsvc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30021
